/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication61;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author manso
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Marchivo = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        SalvarArchivo = new javax.swing.JButton();
        CerrarArchivo = new javax.swing.JButton();
        Mregistros = new javax.swing.JDialog();
        IntroducirRegistro = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Mindices = new javax.swing.JDialog();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        Mestandar = new javax.swing.JDialog();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        CrearCampos = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TipoChar = new javax.swing.JRadioButton();
        TipoInt = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        NombreCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EsLlave = new javax.swing.JRadioButton();
        NoLlave = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaCampos = new javax.swing.JList<>();
        BotonListar = new javax.swing.JButton();
        TipoDeDato = new javax.swing.ButtonGroup();
        Llave = new javax.swing.ButtonGroup();
        CrudCampos = new javax.swing.JPopupMenu();
        EliminarCampos = new javax.swing.JMenuItem();
        ModificarCampos = new javax.swing.JMenuItem();
        Añadir = new javax.swing.JMenuItem();
        ListaRegistros = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDeRegistros = new javax.swing.JList<>();
        jButton9 = new javax.swing.JButton();
        jbr = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        Lab = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        br = new javax.swing.JList<>();
        buscar = new javax.swing.JButton();
        CrudRegistros = new javax.swing.JPopupMenu();
        ModificarRegistros = new javax.swing.JMenuItem();
        BorrarRegistros = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jButton6.setText("Abrir archivo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Nuevo archivo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setText("Salir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        SalvarArchivo.setText("Salvar Archivo");
        SalvarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarArchivoMouseClicked(evt);
            }
        });

        CerrarArchivo.setText("Cerrar Archivo");
        CerrarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MarchivoLayout = new javax.swing.GroupLayout(Marchivo.getContentPane());
        Marchivo.getContentPane().setLayout(MarchivoLayout);
        MarchivoLayout.setHorizontalGroup(
            MarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarchivoLayout.createSequentialGroup()
                .addGroup(MarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MarchivoLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(MarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CerrarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MarchivoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SalvarArchivo)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        MarchivoLayout.setVerticalGroup(
            MarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarchivoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(CerrarArchivo)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(SalvarArchivo)
                .addContainerGap())
        );

        IntroducirRegistro.setText("Introducir Registros");
        IntroducirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducirRegistroActionPerformed(evt);
            }
        });

        jButton16.setText("Modificar Registros");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Buscar Registros");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        jButton18.setText("Borrar Registros");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Listar Registros");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MregistrosLayout = new javax.swing.GroupLayout(Mregistros.getContentPane());
        Mregistros.getContentPane().setLayout(MregistrosLayout);
        MregistrosLayout.setHorizontalGroup(
            MregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MregistrosLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(MregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntroducirRegistro)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        MregistrosLayout.setVerticalGroup(
            MregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MregistrosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(IntroducirRegistro)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addGap(18, 18, 18)
                .addComponent(jButton18)
                .addGap(18, 18, 18)
                .addComponent(jButton19)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jButton20.setText("Crear Indices");

        jButton21.setText("Re Indexar Archivos");

        javax.swing.GroupLayout MindicesLayout = new javax.swing.GroupLayout(Mindices.getContentPane());
        Mindices.getContentPane().setLayout(MindicesLayout);
        MindicesLayout.setHorizontalGroup(
            MindicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MindicesLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(MindicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        MindicesLayout.setVerticalGroup(
            MindicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MindicesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton21)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jButton22.setText("Exportar Excel");

        jButton23.setText("Exportar XML con Schema");

        javax.swing.GroupLayout MestandarLayout = new javax.swing.GroupLayout(Mestandar.getContentPane());
        Mestandar.getContentPane().setLayout(MestandarLayout);
        MestandarLayout.setHorizontalGroup(
            MestandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MestandarLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(MestandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        MestandarLayout.setVerticalGroup(
            MestandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MestandarLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton23)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("A continuacion ingrese los datos del campo a crear:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Tipo de dato");

        TipoDeDato.add(TipoChar);
        TipoChar.setText("Char");

        TipoDeDato.add(TipoInt);
        TipoInt.setText("Int");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del campo");

        NombreCampo.setText(" ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Es llave primaria?");

        Llave.add(EsLlave);
        EsLlave.setText("Si");
        EsLlave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsLlaveActionPerformed(evt);
            }
        });

        Llave.add(NoLlave);
        NoLlave.setText("No");

        jButton11.setText("Crear Campo");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TipoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TipoChar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EsLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NoLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                .addComponent(jButton11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(NombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TipoChar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TipoInt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EsLlave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                        .addComponent(NoLlave)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Crear Campos", jPanel1);

        ListaCampos.setModel(new DefaultListModel());
        ListaCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaCamposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaCampos);

        BotonListar.setText("Listar");
        BotonListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonListarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Campos", jPanel2);

        javax.swing.GroupLayout CrearCamposLayout = new javax.swing.GroupLayout(CrearCampos.getContentPane());
        CrearCampos.getContentPane().setLayout(CrearCamposLayout);
        CrearCamposLayout.setHorizontalGroup(
            CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearCamposLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        CrearCamposLayout.setVerticalGroup(
            CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearCamposLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        EliminarCampos.setText("Eliminar");
        EliminarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCamposActionPerformed(evt);
            }
        });
        CrudCampos.add(EliminarCampos);

        ModificarCampos.setText("Modificar");
        ModificarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarCamposActionPerformed(evt);
            }
        });
        CrudCampos.add(ModificarCampos);

        Añadir.setText("Añadir a Archivo");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });
        CrudCampos.add(Añadir);

        ListaDeRegistros.setModel(new DefaultListModel());
        ListaDeRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDeRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaDeRegistros);

        jButton9.setText("Listar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListaRegistrosLayout = new javax.swing.GroupLayout(ListaRegistros.getContentPane());
        ListaRegistros.getContentPane().setLayout(ListaRegistrosLayout);
        ListaRegistrosLayout.setHorizontalGroup(
            ListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaRegistrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        ListaRegistrosLayout.setVerticalGroup(
            ListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaRegistrosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jLabel5.setText("Introduzca la llave primaria a buscar");

        Lab.setText(" ");

        br.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(br);

        buscar.setText("Buscar");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jbrLayout = new javax.swing.GroupLayout(jbr.getContentPane());
        jbr.getContentPane().setLayout(jbrLayout);
        jbrLayout.setHorizontalGroup(
            jbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbrLayout.createSequentialGroup()
                .addGroup(jbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbrLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lab, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jbrLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jbrLayout.setVerticalGroup(
            jbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbrLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        ModificarRegistros.setText("jMenuItem1");
        ModificarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarRegistrosActionPerformed(evt);
            }
        });

        BorrarRegistros.setText("jMenuItem2");
        BorrarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarRegistrosActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Campos");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Registros");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Indices");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Estandarización");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Marchivo.setModal(true);
        Marchivo.pack();
        Marchivo.setLocationRelativeTo(this);
        Marchivo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Mregistros.setModal(true);
        Mregistros.pack();
        Mregistros.setLocationRelativeTo(this);
        Mregistros.setVisible(true);
     }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Mindices.setModal(true);
        Mindices.pack();
        Mindices.setLocationRelativeTo(this);
        Mindices.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Mestandar.setModal(true);
        Mestandar.pack();
        Mestandar.setLocationRelativeTo(this);
        Mestandar.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        CrearCampos.setModal(true);
        CrearCampos.pack();
        CrearCampos.setLocationRelativeTo(this);
        CrearCampos.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        String tipo;
        int longitud;
        String nombre = NombreCampo.getText();
        boolean llave;
        if (TipoChar.isSelected()) {//verificando de que tipo de dato sera el campo
            tipo = "char";
            longitud=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la longitud"));
        } else {
            tipo = "int";
            longitud=8;
        }
        if (!primaria && EsLlave.isSelected()) {//verificando si el campo sera llave o no
            llave = true;
            primaria=true;
        } else {
            llave = false;
        }
        Campo c = new Campo(nombre, tipo, llave, longitud);
        campos.add(new Campo(nombre, tipo, llave, longitud));
        JOptionPane.showMessageDialog(this, "Campo creado exitosamente");
        NombreCampo.setText("");
        DefaultListModel modelo = (DefaultListModel) ListaCampos.getModel();
        modelo.addElement(new Campo(nombre, tipo, llave, longitud));
    }//GEN-LAST:event_jButton11MouseClicked

    private void EsLlaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsLlaveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EsLlaveActionPerformed

    private void ListaCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaCamposMouseClicked
        if (ListaCampos.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                CrudCampos.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_ListaCamposMouseClicked

    private void ModificarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCamposActionPerformed
        if (ListaCampos.getSelectedIndex() >= 0) {
            DefaultListModel modeloLista = (DefaultListModel) ListaCampos.getModel();
            String nNombre=JOptionPane.showInputDialog("Nombre");
            int nLongitud=Integer.parseInt(JOptionPane.showInputDialog("Longitud"));
            ((Campo) modeloLista.get(ListaCampos.getSelectedIndex())).setNombre(nNombre);//modifico el nombre
            campos.get(ListaCampos.getSelectedIndex()).setNombre(nNombre);
            ((Campo) modeloLista.get(ListaCampos.getSelectedIndex())).setLongitud(nLongitud);//modifico la longitud
            campos.get(ListaCampos.getSelectedIndex()).setLongitud(nLongitud);
            String llave = JOptionPane.showInputDialog("Es llave?(Si/No)");
            boolean nLlave=false;
            if (llave == "si" || llave == "Si") {
                ((Campo) modeloLista.get(ListaCampos.getSelectedIndex())).setLlave(true);
                nLlave=true;
            }
            if (llave == "No" || llave == "no") {
                ((Campo) modeloLista.get(ListaCampos.getSelectedIndex())).setLlave(false);
                nLlave=false;
            }
            campos.get(ListaCampos.getSelectedIndex()).setLlave(nLlave);
            ListaCampos.setModel(modeloLista);
        }
    }//GEN-LAST:event_ModificarCamposActionPerformed

    private void EliminarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCamposActionPerformed

        try{
          if (ListaCampos.getSelectedIndex() >= 0) {
            DefaultListModel modeloLista = (DefaultListModel) ListaCampos.getModel();
            modeloLista.remove(ListaCampos.getSelectedIndex());
            ListaCampos.setModel(modeloLista);
            campos.remove(ListaCampos.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Eliminado exitosamente");
        }  
        }catch(IndexOutOfBoundsException e){
            System.out.println("Borrando....");
        }
         
    }//GEN-LAST:event_EliminarCamposActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
        String titulo = "";
        titulo = JOptionPane.showInputDialog(this, "Ingrese el título del archivo a crear:");
        path = "./" + titulo + ".txt";
        adminArchivos aa = new adminArchivos(path);
        aa.cargarArchivo();
        aa.escribirArchivo();
        titulo = JOptionPane.showInputDialog(this, "Ingrese el título del archivo a crear:");
        String path = "./" + titulo + ".txt";
        fichero = new File(path);
        try {
            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                fw = new FileWriter(fichero, false);
                bw = new BufferedWriter(fw);

                bw.flush();
            } catch (Exception ex) {
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {

        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        /* FileFilter archivosFilter = new FileFilter() {
            //Sobreescribimos el método
            public boolean accept(File file) {
                if (file.getName().endsWith(".txt")) {
                    return true;
                }
                return false;
            }
        };
        String sCarpAct = System.getProperty("user.dir");
        File carpeta = new File(sCarpAct);
        File[] listado = carpeta.listFiles(archivosFilter);
        if (listado == null || listado.length == 0) {
            System.out.println("No hay elementos dentro de la carpeta actual");
            return;
        } else {
            DefaultListModel m = new DefaultListModel();
            for (int i = 0; i < listado.length; i++) {
                m.addElement(listado[i].getName());
                //System.out.println(listado[i].getName());
            }
            //listaArchivos.setModel(m);*/
        
        FileFilter archivosFilter = new FileFilter() {
            //Sobreescribimos el método
            public boolean accept(File file) {
                if (file.getName().endsWith(".txt")) {
                    return true;
                }
                return false;
            }
        };
        String sCarpAct = System.getProperty("user.dir");
        File carpeta = new File(sCarpAct);
        File[] listado = carpeta.listFiles(archivosFilter);
        if (listado == null || listado.length == 0) {
            System.out.println("No hay elementos dentro de la carpeta actual");
            return;
        } else {
            DefaultListModel m = new DefaultListModel();
            for (int i = 0; i < listado.length; i++) {
                m.addElement(listado[i].getName());
                //System.out.println(listado[i].getName());
            }
            //listaArchivos.setModel(m);*/
        if (fichero != null) {
            JOptionPane.showMessageDialog(this, "ya hay un archivo abierto");
        } else {
            fichero = null;
            FileReader fr = null;
            BufferedReader br = null;
            try {
                JFileChooser jfc = new JFileChooser("./");
                FileNameExtensionFilter filtro
                        = new FileNameExtensionFilter(
                                "Archivos de Texto", "txt");
                FileNameExtensionFilter filtro2
                        = new FileNameExtensionFilter(
                                "Imagenes", "jpg", "png", "bmp");
                jfc.setFileFilter(filtro);
                jfc.addChoosableFileFilter(filtro2);
                int seleccion = jfc.showOpenDialog(this);
                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    fichero = jfc.getSelectedFile();
                    fr = new FileReader(fichero);
                    br = new BufferedReader(fr);
                    String nombreArchivo = jfc.getSelectedFile().getName();
                    adminCampos ac = new adminCampos("./" + nombreArchivo);
                    ac.cargarArchivo();
                    for (int i = 0; i < ac.getListacampos().size(); i++) {
                        Campo ctemp = ac.getListacampos().get(i);
                        campos.add(ctemp);
                    }
                    JOptionPane.showMessageDialog(this, "El archivo " + nombreArchivo + " Se abrio correctamente.");
                } //fin if

            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                br.close();
                fr.close();
            } catch (IOException ex) {
            }
        }
    }
        for (Campo campo : campos) {
            if(campo.isLlave()){
                primaria=true;
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Marchivo.setModal(false);
        Marchivo.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
        if (ListaCampos.getSelectedIndex() >= 0) {
            File fichero = null;
            FileReader fr = null;
            BufferedReader br = null;
            FileWriter fw = null;
            BufferedWriter bw = null;
            //textArchivo.setText("");
            try {
                JFileChooser jfc = new JFileChooser("./");
                FileNameExtensionFilter filtro
                        = new FileNameExtensionFilter(
                                "Archivos de Texto", "txt");
                FileNameExtensionFilter filtro2
                        = new FileNameExtensionFilter(
                                "Imagenes", "jpg", "png", "bmp");
                jfc.setFileFilter(filtro);
                jfc.addChoosableFileFilter(filtro2);
                int seleccion = jfc.showOpenDialog(this);
                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    fichero = jfc.getSelectedFile();
                    fr = new FileReader(fichero);
                    br = new BufferedReader(fr);
                    String linea;
                    String texto = "";
                    //textArchivo.setText("");
                    while ((linea = br.readLine()) != null) {
                        texto += linea + "\n";
                    }
                    String c = campos.get(ListaCampos.getSelectedIndex()).toString();
                    texto += c;
                    fw = new FileWriter(fichero);
                    bw = new BufferedWriter(fw);
                    bw.write(texto);
                    bw.flush();
                    JOptionPane.showMessageDialog(this, "Campo añadido exitosamente");
                } //fin if

            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                bw.close();
                fw.close();
                br.close();
                fr.close();
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_AñadirActionPerformed

    private void IntroducirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducirRegistroActionPerformed
        Scanner entrada=new Scanner(System.in);
        Registropersona register=new Registropersona();
        register.setCampos(campos);
        ArrayList<String> atributos=new ArrayList();
        for (Campo campo : campos) {
            String dato=JOptionPane.showInputDialog(this,"Ingresar "+ campo.getNombre());
            String datoc=dato.substring(0, campo.getLongitud());
            if (campo.getTipo().equals("int")){
                boolean si=esNumero(datoc);
                while(!si){
                    JOptionPane.showMessageDialog(this,"Tipo de dato no compatible con el campo solicitado");
                    datoc=JOptionPane.showInputDialog(this,"Ingresar "+ campo.getNombre());
                    si=esNumero(datoc);
                }
                   atributos.add(datoc);   
            } 
            else{
                atributos.add(datoc);
            }
        }
        register.setAtributos(atributos);
        registros.add(register);
        
          
    }//GEN-LAST:event_IntroducirRegistroActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        ListaRegistros.setModal(true);
        ListaRegistros.pack();
        ListaRegistros.setLocationRelativeTo(this);
        ListaRegistros.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void BotonListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonListarMouseClicked
        DefaultListModel modelo = new DefaultListModel ();
        for (int i=0;i<campos.size();i++){
            Campo ctemp=campos.get(i);
            modelo.addElement(ctemp);
        }
        ListaCampos.setModel(modelo);
    }//GEN-LAST:event_BotonListarMouseClicked

    private void SalvarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarArchivoMouseClicked
        
        PrintWriter writer=null;
        try {
            writer = new PrintWriter(fichero);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        writer.print("");
        writer.close();
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(fichero, false);
            bw = new BufferedWriter(fw);
            for (Campo t : campos) {
                bw.write(t.getNombre() + ";");
                bw.write(t.getTipo() + ";");
                bw.write(t.isLlave()+ ";");
                bw.write(t.getLongitud() + ";");
                
            }
            bw.flush();
        } catch (Exception ex) {
        }
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this,"El archivo se guardo correctamente");
    }//GEN-LAST:event_SalvarArchivoMouseClicked

    private void CerrarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarArchivoMouseClicked
        FileReader fr = null;
        BufferedReader br = null;
        try {
            fr = new FileReader(fichero);
            br = new BufferedReader(fr);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        int input = JOptionPane.showConfirmDialog(null, "Quiere Cerrar el Archivo?");
        // 0=yes, 1=no, 2=cancel
        if (input == 0) {
            if (fichero.exists()) {
                try {
                    fr.close();
                    br.close();
                } catch (IOException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            campos.clear();
            DefaultListModel modelo = new DefaultListModel ();
            for (int i=0;i<campos.size();i++){
                Campo ctemp=campos.get(i);
                modelo.addElement(ctemp);
            }
            ListaCampos.setModel(modelo);
            
        }
           fichero = null;
           JOptionPane.showMessageDialog(this, "El archivo ha sido cerrado");
           
        //campos.clear();
    }//GEN-LAST:event_CerrarArchivoMouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        
        DefaultListModel modelo = new DefaultListModel ();
        for (int i=0;i<registros.size();i++){
            Registropersona rtemp=registros.get(i);
            modelo.addElement(rtemp);
        }
        ListaDeRegistros.setModel(modelo);
    
    }//GEN-LAST:event_jButton9MouseClicked
    public static boolean esNumero(String strNum) {
    if (strNum == null) {
        return false;
    }
    try {
        double d = Double.parseDouble(strNum);
    } catch (NumberFormatException nfe) {
        return false;
    }
    return true;
}
    
    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        ListaRegistros.setModal(true);
        ListaRegistros.pack();
        ListaRegistros.setLocationRelativeTo(this);
        ListaRegistros.setVisible(true);
    }//GEN-LAST:event_jButton19MouseClicked

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
         
        DefaultListModel modelo = new DefaultListModel();
        for (Campo campo : campos) {
            if (campo.isLlave() == true) {
                for (int i = 0; i < registros.size(); i++) {
                    if (Lab.getText().equals(registros.get(i).getAtributos().get(i))) {
                        Registropersona rtemp = registros.get(i);
                        modelo.addElement(rtemp);
                            br.setModel(modelo);
                    }
                }
            }
        }
    }//GEN-LAST:event_buscarMouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        jbr.setModal(true);
        jbr.pack();
        jbr.setLocationRelativeTo(this);
        jbr.setVisible(true);
    }//GEN-LAST:event_jButton17MouseClicked

    private void ListaDeRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeRegistrosMouseClicked
        if (ListaDeRegistros.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                CrudRegistros.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_ListaDeRegistrosMouseClicked

    private void BorrarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarRegistrosActionPerformed
        if (ListaDeRegistros.getSelectedIndex() >= 0) {
            DefaultListModel modeloLista = (DefaultListModel) ListaDeRegistros.getModel();
            modeloLista.remove(ListaDeRegistros.getSelectedIndex());
            ListaDeRegistros.setModel(modeloLista);
            registros.remove(ListaDeRegistros.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Eliminado exitosamente");
        }
    }//GEN-LAST:event_BorrarRegistrosActionPerformed

    private void ModificarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarRegistrosActionPerformed
        if(ListaDeRegistros.getSelectedIndex()>=0){
            DefaultListModel modeloLista = (DefaultListModel) ListaDeRegistros.getModel();
            for (Campo campo : campos) {
            int i=0;
            String dato=JOptionPane.showInputDialog(this,"Ingresar "+ campo.getNombre());
            ((Registropersona) modeloLista.get(ListaDeRegistros.getSelectedIndex())).getAtributos().set(i,dato);
            registros.get(ListaDeRegistros.getSelectedIndex()).getAtributos().set(i,dato);
            i++;
        }
        }
         
    }//GEN-LAST:event_ModificarRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Añadir;
    private javax.swing.JMenuItem BorrarRegistros;
    private javax.swing.JButton BotonListar;
    private javax.swing.JButton CerrarArchivo;
    private javax.swing.JDialog CrearCampos;
    private javax.swing.JPopupMenu CrudCampos;
    private javax.swing.JPopupMenu CrudRegistros;
    private javax.swing.JMenuItem EliminarCampos;
    private javax.swing.JRadioButton EsLlave;
    private javax.swing.JButton IntroducirRegistro;
    private javax.swing.JTextField Lab;
    private javax.swing.JList<String> ListaCampos;
    private javax.swing.JList<String> ListaDeRegistros;
    private javax.swing.JDialog ListaRegistros;
    private javax.swing.ButtonGroup Llave;
    private javax.swing.JDialog Marchivo;
    private javax.swing.JDialog Mestandar;
    private javax.swing.JDialog Mindices;
    private javax.swing.JMenuItem ModificarCampos;
    private javax.swing.JMenuItem ModificarRegistros;
    private javax.swing.JDialog Mregistros;
    private javax.swing.JRadioButton NoLlave;
    private javax.swing.JTextField NombreCampo;
    private javax.swing.JButton SalvarArchivo;
    private javax.swing.JRadioButton TipoChar;
    private javax.swing.ButtonGroup TipoDeDato;
    private javax.swing.JRadioButton TipoInt;
    private javax.swing.JList<String> br;
    private javax.swing.JButton buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jbr;
    // End of variables declaration//GEN-END:variables
    ArrayList<Campo> campos = new ArrayList();
    ArrayList<Registropersona> registros=new ArrayList();
    File fichero = null;
    String FileName;
    Registropersona p;
    Registro r;
    boolean primaria=false;
    String path;
}
